---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'

useGitignore: true

language: en,eo,typescript,javascript
#languageSettings: typescript, javascript

# promised
words:
  - tilog
  - gloriajun
  # styled-component
  - clsx
## not promised, but it has to allow
#ignoreWords:
#  - xx
