name: deploy-github-actions
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
    # branches: [main]
    paths-ignore:
      - 'apps/doc/docs/**'
#      - 'apps/website/devlogs/**'
#      - 'apps/website/trouble-shootings/**'
      - '.husky/**'
      - '.vscode/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache yarn dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint:all

      # - name: Unit Test
      #   run: |
      #     yarn run test
      #     yarn run coverage

      - name: Build Website
        run: yarn run build doc
